# Generated by Django 4.2 on 2023-04-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accesorios',
            fields=[
                ('IdAccesorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAccesorio', models.CharField(max_length=500)),
                ('cantidadAccesorio', models.CharField(max_length=500)),
                ('precioAccesorio', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='perritos',
            fields=[
                ('IdPerro', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePerro', models.CharField(max_length=500)),
                ('razaPerro', models.CharField(max_length=500)),
                ('edadPerro', models.CharField(max_length=500)),
            ],
        ),
    ]
